# Generated by Django 4.0.1 on 2022-01-31 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('comment', models.CharField(max_length=20000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.topic')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
